"use client";
import Navbar from "@/components/navbar/navbar";
import localFont from "next/font/local";
import { useState } from "react";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Hotel Management System",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLightTheme, setIsLightTheme] = useState(false);

  const toggleColorTheme = () => {
    setIsLightTheme(!isLightTheme);
  };
  return (
    <html lang="en" data-theme={isLightTheme ? "dark" : "light"}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar
          toggleColorTheme={toggleColorTheme}
          isLightTheme={isLightTheme}
        />
        {children}
      </body>
    </html>
  );
}
